# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: coliveramispireta
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-crud-guru-challenge

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    TABLE_NAME: ${self:service}-tickets-${sls:stage}
    MEMBERS_TABLE: ${self:service}-members-${sls:stage}
    AUTH_TOKEN: ${ssm:/crud-guru/${sls:stage}/auth-token}
    USER_POOL_ID: ${ssm:/myapp/userpool-id}
    USER_POOL_NAME: ${ssm:/myapp/userpool-name}
  tags:
    project: crud-guru
    owner: colivera
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:${aws:region}:${aws:accountId}:*
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource: 
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.TABLE_NAME}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.MEMBERS_TABLE}

plugins:
  - serverless-offline

package:
  individually: true

functions: ${file(./serverless-functions/index.yml)}
resources: ${file(./serverless-resources/dynamodb.yml)}
